### ISSUE TITLE
Recursive model bugs

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#117]
Probably, the problem is checking the database columns in the initialization process. 

```
Error: Category model doesn't have the following columns on the database; "categories.category_id"
    at checkModelColumnsOrFail (file:///home/ozzy/Desktop/github/axe-api/axe-api/src/resolvers/checkModelColumns.js:61:11)
    at checkHasManyRelation (file:///home/ozzy/Desktop/github/axe-api/axe-api/src/resolvers/checkModelColumns.js:77:3)
    at checkRelationColumnsOrFail (file:///home/ozzy/Desktop/github/axe-api/axe-api/src/resolvers/checkModelColumns.js:100:5)
    at file:///home/ozzy/Desktop/github/axe-api/axe-api/src/resolvers/checkModelColumns.js:111:5
    at Array.forEach (<anonymous>)
    at default (file:///home/ozzy/Desktop/github/axe-api/axe-api/src/resolvers/checkModelColumns.js:105:10)
    at Server._analyzeModels (file:///home/ozzy/Desktop/github/axe-api/axe-api/src/Server.js:72:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.listen (file:///home/ozzy/Desktop/github/axe-api/axe-api/src/Server.js:31:5)
```

**Comment by ozziest** [comment]
We should update the documentation because we don't use `children` keyword as a static url keyword.
