### ISSUE TITLE
dev-kit installation does not work on the arch linux terminal

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#130]
```bash
➜  axe-api git:(master) npm run dev-kit                             

> axe-api@0.20.3 dev-kit
> ts-node-dev --respawn --clear dev-kit.ts

/usr/lib/node_modules/ts-node-dev/node_modules/resolve/lib/sync.js:113
    throw err;
    ^

Error: Cannot find module 'dev-kit.ts' from '/home/xxx/Desktop/axe-api'
    at Function.resolveSync [as sync] (/usr/lib/node_modules/ts-node-dev/node_modules/resolve/lib/sync.js:111:15)
    at resolveRequest (/usr/lib/node_modules/ts-node-dev/lib/resolveMain.js:18:24)
    at exports.resolveMain (/usr/lib/node_modules/ts-node-dev/lib/resolveMain.js:30:20)
    at exports.runDev (/usr/lib/node_modules/ts-node-dev/lib/index.js:53:30)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node-dev/lib/bin.js:136:4)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  code: 'MODULE_NOT_FOUND'
}

Node.js v19.3.0
```

In the installation process, we are getting this error;

```bash
➜  axe-api git:(master) npm run dev-kit:install

> axe-api@0.20.3 dev-kit:install
> sh ./scripts/dev-kit-install.sh

Cloning into 'temp-kit'...
remote: Enumerating objects: 319, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 319 (delta 24), reused 20 (delta 12), pack-reused 270
Receiving objects: 100% (319/319), 458.77 KiB | 694.00 KiB/s, done.
Resolving deltas: 100% (153/153), done.
mv: cannot stat 'temp-kit/dev-kit.sh': No such file or directory
sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs https://knexjs.org/guide/query-builder.html#insert).
Batch 1 run: 1 migrations
\ndev-kit has been installed.\n
```

**Comment by ozziest** [comment]
https://stackoverflow.com/a/17744637/1679827
